version: '2'
services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432"

  web:
    build: .
    command: node server.js
    ports:
      - "3000:3000"
    links:
      - postgres

  test:
    build: .
    command: npm test
    depends_on:
      - postgres
