apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: node-api
  name: node-api
spec:
  ports:
  - name: "80-tcp"
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    service: node-api
  type: LoadBalancer
status:
  loadBalancer: {}
