steps:
  - command: docker-compose run test
    label: test

  - wait

  - command: ./scripts/docker_heroku_deploy.sh
    label: "deploy staging :shipit:"
    env:
      HEROKU_APP_NAME: node-api-staging
      CI_ENVIRONMENT_NAME: staging

  - block: ":shipit: Release this shit"

  - command: ./scripts/docker_heroku_deploy.sh
    label: "deploy production :shipit:"
    env:
      HEROKU_APP_NAME: node-api-production
      CI_ENVIRONMENT_NAME: production

  - command: echo "hello"
    label: something else
